# Generated by Django 3.2.12 on 2022-04-05 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('forWhichClazz', models.CharField(max_length=255)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('branch', models.CharField(blank=True, choices=[('AIKIDO', 'AIKIDO'), ('WING CHUN', 'WING CHUN'), ('WUSHU', 'WUSHU'), ('BUDAKADIO', 'BUDAKADIO'), ('JEET KUNE DO KULELKAVIDO', 'JEET KUNE DO KULELKAVIDO')], max_length=128, null=True, verbose_name='Seçiniz')),
                ('isFirst', models.BooleanField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wushu.categoryitem')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Şehir')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Ülke')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc', models.CharField(blank=True, max_length=120, null=True)),
                ('height', models.CharField(blank=True, max_length=120, null=True)),
                ('weight', models.CharField(blank=True, max_length=120, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=120, null=True, verbose_name='Doğum Yeri')),
                ('motherName', models.CharField(blank=True, max_length=120, null=True, verbose_name='Anne Adı')),
                ('fatherName', models.CharField(blank=True, max_length=120, null=True, verbose_name='Baba Adı')),
                ('profileImage', models.ImageField(blank=True, default='profile/user.png', null=True, upload_to='profile/', verbose_name='Profil Resmi')),
                ('birthDate', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('bloodType', models.CharField(choices=[('AB Rh+', 'AB Rh+'), ('AB Rh-', 'AB Rh-'), ('A Rh+', 'A Rh+'), ('A Rh-', 'A Rh-'), ('B Rh+', 'B Rh+'), ('B Rh-', 'B Rh-'), ('0 Rh+', '0 Rh+'), ('0 Rh-', '0 Rh-')], default='AB Rh+', max_length=128, verbose_name='Kan Grubu')),
                ('gender', models.CharField(choices=[('Erkek', 'Erkek'), ('Kadın', 'Kadın')], default='Erkek', max_length=128, verbose_name='Cinsiyeti')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TaoluCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=255)),
                ('isDuilian', models.BooleanField(blank=True, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('operationDate', models.DateTimeField(auto_now_add=True)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('url', models.CharField(blank=True, max_length=120, null=True)),
                ('is_parent', models.BooleanField(default=True)),
                ('is_show', models.BooleanField(default=True)),
                ('fa_icon', models.CharField(blank=True, max_length=120, null=True)),
                ('sorting', models.IntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wushu.menucoach')),
                ('permission', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MenuAthlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('url', models.CharField(blank=True, max_length=120, null=True)),
                ('is_parent', models.BooleanField(default=True)),
                ('is_show', models.BooleanField(default=True)),
                ('fa_icon', models.CharField(blank=True, max_length=120, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wushu.menuathlete')),
                ('permission', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MenuAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('url', models.CharField(blank=True, max_length=120, null=True)),
                ('is_parent', models.BooleanField(default=True)),
                ('is_show', models.BooleanField(default=True)),
                ('fa_icon', models.CharField(blank=True, max_length=120, null=True)),
                ('sorting', models.IntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wushu.menuadmin')),
                ('permission', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('url', models.CharField(blank=True, max_length=120, null=True)),
                ('is_parent', models.BooleanField(default=True)),
                ('is_show', models.BooleanField(default=True)),
                ('fa_icon', models.CharField(blank=True, max_length=120, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wushu.menu')),
                ('permission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MenuPermission', to='auth.permission')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('operationDate', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=150, null=True)),
                ('ip', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Üye Rolü')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('branch', models.CharField(choices=[('AIKIDO', 'AIKIDO'), ('WING CHUN', 'WING CHUN'), ('WUSHU', 'WUSHU'), ('BUDAKADIO', 'BUDAKADIO'), ('JEET KUNE DO KULELKAVIDO', 'JEET KUNE DO KULELKAVIDO')], max_length=128, verbose_name='Branş')),
                ('isActive', models.BooleanField(default=False)),
                ('licenseNo', models.CharField(max_length=255)),
                ('expireDate', models.DateField()),
                ('startDate', models.DateField()),
                ('status', models.CharField(choices=[('Onaylandı', 'Onaylandı'), ('Onaya Gönderildi', 'Onaya Gönderildi'), ('Reddedildi', 'Reddedildi'), ('Beklemede', 'Beklemede')], default='Beklemede', max_length=128, verbose_name='Onay Durumu')),
                ('lisansPhoto', models.FileField(upload_to='lisans/', verbose_name='Lisans')),
                ('reddetwhy', models.CharField(blank=True, max_length=255, null=True)),
                ('cityHeadShip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wushu.city')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelType', models.CharField(choices=[('VISA', 'VISA'), ('GRADE', 'GRADE'), ('BELT', 'BELT')], max_length=128, verbose_name='Leveller')),
                ('branch', models.CharField(choices=[('AIKIDO', 'AIKIDO'), ('WING CHUN', 'WING CHUN'), ('WUSHU', 'WUSHU'), ('BUDAKADIO', 'BUDAKADIO'), ('JEET KUNE DO KULELKAVIDO', 'JEET KUNE DO KULELKAVIDO')], max_length=128, verbose_name='Branş')),
                ('isActive', models.BooleanField(default=False)),
                ('startDate', models.DateField()),
                ('expireDate', models.DateField(blank=True, null=True)),
                ('durationDay', models.IntegerField(blank=True, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Onaylandı', 'Onaylandı'), ('Onaya Gönderildi', 'Onaya Gönderildi'), ('Reddedildi', 'Reddedildi'), ('Beklemede', 'Beklemede')], default='Beklemede', max_length=128, verbose_name='Onay Durumu')),
                ('dekont', models.FileField(blank=True, null=True, upload_to='dekont/', verbose_name='Dekont ')),
                ('form', models.FileField(upload_to='form/', verbose_name='Form ')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wushu.city', verbose_name='İl')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wushu.categoryitem')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CompetitionCategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete', models.ManyToManyField(to='wushu.Athlete')),
                ('categori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wushu.taolucategory', verbose_name='Categori')),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('startDate', models.DateTimeField()),
                ('finishDate', models.DateTimeField()),
                ('location', models.CharField(max_length=1000)),
                ('branch', models.CharField(choices=[('AIKIDO', 'AIKIDO'), ('WING CHUN', 'WING CHUN'), ('WUSHU', 'WUSHU'), ('BUDAKADIO', 'BUDAKADIO'), ('JEET KUNE DO KULELKAVIDO', 'JEET KUNE DO KULELKAVIDO')], max_length=128, verbose_name='Branş')),
                ('subBranch', models.CharField(choices=[('SANDA', 'SANDA'), ('TAOLU', 'TAOLU')], max_length=128, verbose_name='Alt Branş')),
                ('status', models.CharField(choices=[('Ön Kayıt Açık', 'Ön Kayıt Açık'), ('Ön Kayıt Tamamlandı', 'Ön Kayıt Tamamlandı'), ('Beklemede', 'Beklemede')], default='Beklemede', max_length=128, verbose_name='Kayıt Durumu')),
                ('type', models.CharField(choices=[('Uluslararası', 'Uluslararası'), ('Okullar Arası', 'Okullar Arası'), ('Üniversiteler Arası', 'Üniversiteler Arası'), ('Ulusal', 'Ulusal')], default='Ulusal', max_length=128, verbose_name='Türü')),
                ('registerStartDate', models.DateTimeField(blank=True, db_column='registerStartDate', null=True)),
                ('registerFinishDate', models.DateTimeField(blank=True, db_column='registerFinishDate', null=True)),
                ('categori', models.ManyToManyField(to='wushu.CompetitionCategori')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postalCode', models.CharField(blank=True, max_length=120, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=120, null=True)),
                ('phoneNumber2', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wushu.city', verbose_name='İl')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wushu.country', verbose_name='Ülke')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('communication', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wushu.communication')),
                ('grades', models.ManyToManyField(blank=True, null=True, related_name='CoachGrades', to='wushu.Level')),
                ('person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wushu.person')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visa', models.ManyToManyField(blank=True, null=True, related_name='CoachVisa', to='wushu.Level')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='athlete',
            name='belts',
            field=models.ManyToManyField(to='wushu.Level'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wushu.coach'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='communication',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wushu.communication'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='licenses',
            field=models.ManyToManyField(to='wushu.License'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wushu.person'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
