from .Athlete import Athlete
from .CategoryItem import CategoryItem
from .Federation import Federation
from .Communication import Communication
from .Competition import Competition
from .CompetitionCategori import CompetitionCategori
from .Country import Country
from .EnumFields import EnumFields
from .Logs import Logs
from .Menu import Menu
from .MenuAdmin import MenuAdmin
from .MenuAthlete import MenuAthlete
from .MenuCoach import MenuCoach
from .Person import Person
from .TaoluCategory import TaoluCategory
from .YearsSandaCategory import YearsSandaCategory
from .YearsTaoluCategory import YearsTaoluCategory
from .TaoluAthlete import TaoluAthlete
from .SandaAthlete import SandaAthlete
from .Judge import Judge
from .Observer import Observer
from .Officer import Officer
from .Coach import Coach
from .SandaAthlete import SandaAthlete
from .SandaCoach import SandaCoach
from .SandaOfficer import SandaOfficer
from .SandaObserver import SandaObserver
from .SandaJudge import SandaJudge
from .TaoluCoach import TaoluCoach
from .TaoluObserver import TaoluObserver
from .TaoluOfficer import TaoluOfficer
from .TaoluJudge import TaoluJudge
from .SandaWeightCategory import SandaWeightCategory
